### ISSUE TITLE
[1.12.2] Simple Harvest 1.12-1.2.6-18 works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [TehNut-Mods/Harvest#11]
[Simple Harvest 1.12-1.2.6-18](https://minecraft.curseforge.com/projects/simpleharvest/files/2475234) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by TehNut** [comment]
![why](https://i.imgur.com/M9COucX.gif)

**Comment by sandalle** [comment]
Thank you for the double quick turnaround, @TehNut . ;)
