### ISSUE TITLE
1.13.2 Forge Version Rightclick Bug 

### ISSUE THREAD

**Issue by TomKell** [TehNut-Mods/Harvest#14]
Hello!

When you open up the crafting table/furnace/chest or something else and you have a block or something in your hands, it places the block in front of the crafting table/furnace/chest...

Hope this information can help you!

**Comment by TehNut** [comment]
Until Curse approves it, you can download it [here](https://tehnut.info/maven/info/tehnut/harvest/Harvest/1.13.2-1.2.9-22/Harvest-1.13.2-1.2.9-22.jar)

**Comment by TomKell** [comment]
Thank you for the fast and helpful support!
