### ISSUE TITLE
Failed to find seed

### ISSUE THREAD

**Issue by xAlicatt** [TehNut-Mods/Harvest#17]
I left this in comments, and then realized that you have an issue tracker, I just missed it earlier because of the Curse site redesign/restructure. 

Fabric Loader Version: 0.4.8 Build 155
Fabric API Ver: ~fabric-api-0.3.0+build.187.jar~fabric-api-0.3.0+build.198.jar
Simple Harvest Ver: Harvest-1.14-fabric-1.0.4.jar

Log: https://paste.dimdev.org/ivewafixiz.cs 

With the extra logging enabled, it seems like it's failing because of something to do with seeds? I'm going to guess based on your question in Discord earlier that the config file is missing a value that would make it work...However, I am using the default generated config, since I can *read* json (usually) but do not understand the syntax well enough to write it. I'm sure if I knew how to do so, I could fix this myself.

**Comment by TehNut** [comment]
Is the `harvest:seeds` item tag populated? That is what harvest uses to find seeds in the drop list. 

Another problem could be a mod or data pack modifying the drop list.

**Comment by xAlicatt** [comment]
I don't know what that means? I'm not a developer, The config file is the default that gets generated when the mod is loaded. 

```{
  "exhaustionPerHarvest": 0.005,
  "additionalLogging": true,
  "crops": [
    {
      "block": "minecraft:wheat",
      "states": {
        "age": "7"
      }
    },
    {
      "block": "minecraft:nether_wart",
      "states": {
        "age": "3"
      }
    },
    {
      "block": "minecraft:carrots",
      "states": {
        "age": "7"
      }
    },
    {
      "block": "minecraft:potatoes",
      "states": {
        "age": "7"
      }
    },
    {
      "block": "minecraft:beetroots",
      "states": {
        "age": "3"
      }
    }
  ]
}```

**Comment by xAlicatt** [comment]
None of the other mods we use alter anything to do with crops or seeds. And none have been added since the 1.14.3 update anyway...which is when this stopped working for us.

Modlist: 
+BeaconFlight
+Slash Enderchest
+Deathmaps
+Discord Link
+FoamFix
+Infinity Fix
+Leaf Decay
+Locate Biome
+SmoothBedrock
+Vanilla Death Chest

Datapack list: 
+Ships
+Coordinates HUD
+Custom Villager Shops
+Customizable Armor Stands
+Double Shulker Shells
+Headchanger
+Illager Fortresses
+More mob heads
+1 player sleep
+Silence mobs
+and a few of the VanillaTweaks recipe additions

**Comment by xAlicatt** [comment]
Hi. Could you please explain what you mean by is the "harvest:seeds" tag populated?

**Comment by xAlicatt** [comment]
@tehnut This is not working for us on our multiplayer server...server-side only. I am using out of the box settings and have provided a log and our mod/datapack list. It was working before we updated to 1.14.3. I have not changed any of our mods or datapacks since before it stopped working.

I cannot fix this myself. I need your help. Could you please help me figure out the issue?

**Comment by xAlicatt** [comment]
Datapack was disabled. Fixed.

If anyone else runs into this issue: check your datapacks and make sure Harvest is enabled.
