### ISSUE TITLE
Suggestion: Don't harvest seeds

### ISSUE THREAD

**Issue by cyberpunkbln** [TehNut-Mods/Harvest#2]
Hello,

was it possible to set an option with option-file or so, that the right-click harvest don't harvest seeds?

thx

**Comment by TehNut** [comment]
What?

**Comment by cyberpunkbln** [comment]
Hello,
i mean that seed drops from wheat or other seed based food, don't drop this seed then i harvest with right click and only drop seed when i push it with left?

**Comment by TehNut** [comment]
Are you asking why modders crops aren't working? You need to add them to the config.

**Comment by cyberpunkbln** [comment]
No i use TorosQuest and when i break the block the Reputation goes down and when i harvest right, the Repution dont affected. Now i found when i harvest some i should only geed the food like wheat and others, not the seeds. But was only a Feature Request not so important.

**Comment by TehNut** [comment]
This would be on their end to implement.
