### ISSUE TITLE
Doesnt work with Aubergine from Mystical World

### ISSUE THREAD

**Issue by Sunekaer** [TehNut-Mods/Harvest#22]
Hi 

From console
> [14:06:15] [Server thread/INFO]: [DEBUG] Failed to find a seed for Block{mysticalworld:aubergine_crop}[age=7]
> [14:06:15] [Server thread/INFO]: [DEBUG] Attempted crop harvest with result FAIL has completed

https://github.com/MysticMods/MysticalWorld/blob/1.14/src/main/java/epicsquid/mysticalworld/blocks/AubergineCropBlock.java

**Comment by TehNut** [comment]
Did you add the seed item to the `harvest:seeds` tag?

**Comment by Sunekaer** [comment]
Well its not my mod, so..
Why you making your own tag and not using forge's seed tag?

**Comment by TehNut** [comment]
Because I didn't know Forge had a seed tag, and mine existed before theirs did.

Also, the entire point of tags is that the user can add to them, you can easily add their seed to the tag.
