### ISSUE TITLE
[Request] 1.15.2 without Fabric API

### ISSUE THREAD

**Issue by Floris0106** [TehNut-Mods/Harvest#23]
It should be possible, but i dont know if it makes any sense. For me it does, as i want to use carpet autocraftingtable without fabric api (the two cause a weird conflict)

**Comment by TehNut** [comment]
I'm not sure I want to implement this. The point of using Fabric API is to maintain compatibility between mods. If a mod is not working with the API developed by the Fabric team itself, they should probably fix that conflict themselves.

**Comment by TehNut** [comment]
Yes, decided against this for the reasons above.
