### ISSUE TITLE
[Request] 1.16.x support

### ISSUE THREAD

**Issue by NotNite** [TehNut-Mods/Harvest#24]
The mod crashes the server when I start with the 1.15 version (expected), will there be an update? Several players on my server rely on this.

**Comment by TehNut** [comment]
~~Try the 1.16 build.~~

I'm dumb I thought this was the hwyla repo... Yes there will be a 1.16 version

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/simpleharvest/files/2989916

Not really sure what would have caused it to crash as nothing seemed out of place in dev, but there we go.
