### ISSUE TITLE
[MC 1.11.2] Caught exception from Harvest (harvest) after updating to 

### ISSUE THREAD

**Issue by sandalle** [TehNut-Mods/Harvest#4]
After updating to Simple Harvest 1.2.2-14 on Minecraft 1.11.2, I get the following crash-report on both server and client: 

I removed my harvest.json from the prior version as new configs were mentioned (new file is harvest_config.json). Restoring the old config (harvest.json) did not remedy the crash: 
[crash-2017-06-25_08.31.43-client.txt](https://github.com/TehNut/Harvest/files/1100415/crash-2017-06-25_08.31.43-client.txt)

**Comment by TehNut** [comment]
Ah, I forgot to remove support for 1.11 in the latest build as I had to re-compile to support Forge's new registry system. Downgrade to 1.2.1-13 to fix this.

I'll unmark it on Curse.

**Comment by sandalle** [comment]
Thanks, 1.2.1-13 works. :)
