### ISSUE TITLE
1.12-1.2.2-14 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [TehNut-Mods/Harvest#6]
Notes:
     on startup

crash report:
https://gist.github.com/60ee988409a8389d43b6e8687fcb5b10

fml server latest:
https://gist.github.com/d4a095e0f42d9febbbbaa7024f6af9d6

possibly related: #5

**Comment by TehNut** [comment]
Dupe.
