### ISSUE TITLE
Some of Rustic's Herbs do not want to harvest on right click

### ISSUE THREAD

**Issue by Serifina** [TehNut-Mods/Harvest#7]
MC 1.12.1
Forge 14.22.0.2.2467
SimpleHarvest 1.12-1.2.4-16
Rustic 0.4.1
[harvest_config.json](https://pastebin.com/2zuNEs0u)

4 of Rustic's herbs work correctly (Cloudsbluff, Core Root, Marsh Mallow, and Ginseng). The other 8 (Horsetail, Deathstalk Mushroom, Cohosh, Chamomile, Blood Orchid, Aloe Vera, Mooncap Mushroom, and Wind Thistle) do not work. Every other crop I've added has worked correctly. I'm not sure what's wrong here. Breaking the herbs work normally, and as far as I can see, they're all implemented the same, so I'm at a loss.

**Comment by TehNut** [comment]
I'll take a look when I get home. As a guess, I'll say the drops may not contain an IPlantable.

**Comment by Serifina** [comment]
Thanks.

**Comment by TehNut** [comment]
I looked and this seems to be an improper implementation of the herbs on Rustic's side. From what I'm seeing in the source, the items don't actually ever get registered, so the crop tries to drop `minecraft:air`, which is obviously not an `IPlantable`. 

On another note, I will be pushing a new update that makes `finalBlock` optional and will default to the same block with a meta of 0. So your JSON length can be cut in half.

**Comment by Serifina** [comment]
Thanks for the help.
